// <auto-generated />
namespace DomainModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _220716_Size_quantity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_220716_Size_quantity));
        
        string IMigrationMetadata.Id
        {
            get { return "201607221405398_22.07.16_Size_quantity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
